version: "3.9"
services:
    seq:
        image: datalust/seq 
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
        ports:
          - 5341:80
        volumes:
          - seq:/data
volumes:
  seq:
    driver: local

